---
booktitle: Proceedings of the 8th Machine Learning for Healthcare Conference
volume: '219'
shortname: MLHC
year: '2023'
start: 2023-08-11
end: 2023-08-12
published: 2023-12-22
url: https://proceedings.mlr.press
conference_number: '8'
layout: proceedings
series: Proceedings of Machine Learning Research
publisher: PMLR
issn: 2640-3498
id: MLHC-2023
month: 0
cycles: false
bibtex_editor: Deshpande, Kaivalya and Fiterau, Madalina and Joshi, Shalmali and Lipton,
  Zachary and Ranganath, Rajesh and Urteaga, I\~nigo and Yeung, Serene
editor:
- given: Kaivalya
  family: Deshpande
- given: Madalina
  family: Fiterau
- given: Shalmali
  family: Joshi
- given: Zachary
  family: Lipton
- given: Rajesh
  family: Ranganath
- given: Iñigo
  family: Urteaga
- given: Serene
  family: Yeung
title: Proceedings of Machine Learning Research
description: |
  Proceedings of the 8th Machine Learning for Healthcare Conference
    Held in New York, USA on 11-12 August 2023

  Published as Volume 219 by the Proceedings of Machine Learning Research on 22 December 2023.

  Volume Edited by:
    Kaivalya Deshpande
    Madalina Fiterau
    Shalmali Joshi
    Zachary Lipton
    Rajesh Ranganath
    Iñigo Urteaga
    Serene Yeung

  Series Editors:
    Neil D. Lawrence
date_str: 11--12 Aug
author:
  name: PMLR
baseurl: "/v219"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: mlresearch/jekyll-theme
style: pmlr
permalink: "/:title.html"
ghub:
  edit: true
  repository: v219
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
volume_type: Volume
volume_dir: v219
email: ''
conference:
  name: Machine Learning for Healthcare Conference
  url:
  location: New York, USA
  dates:
  - 2023-08-11
  - 2023-08-12
analytics:
  google:
    tracking_id: UA-92432422-1
orig_bibfile: "/Users/neil/mlresearch/v219/MLHC23_Proceedings.bib"
# Site settings
# Original source:  /Users/neil/mlresearch/v219/MLHC23_Proceedings.bib
